# inventario_lab2.py — auto-generado por ssh_test_lab2.py (2026-05-17 22:02:39)
# Importar en verificador_lab2.py:
#   from inventario_lab2 import DISCOVERED_INVENTORY

DISCOVERED_INVENTORY = {
    "CPE-HQ": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-HQ", "username": "admin", "password": "admin", "via": "nombre"},
    "CPE-HQ-BK": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-HQ-BK", "username": "admin", "password": "admin", "via": "nombre"},
    "CPE-BRANCH": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH", "username": "admin", "password": "admin", "via": "nombre"},
    "CPE-BRANCH-BK": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH-BK", "username": "admin", "password": "admin", "via": "nombre"},
    "CPE-BRANCH2": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH2", "username": "admin", "password": "admin", "via": "nombre"},
    "CPE-BRANCH2-BK": {"host": "clab-ISP-TDP-CLARO-IOL-CPE-BRANCH2-BK", "username": "admin", "password": "admin", "via": "nombre"},
    "M1": {"host": "clab-ISP-TDP-CLARO-IOL-M1", "username": "admin", "password": "admin", "via": "nombre"},
    "M2": {"host": "clab-ISP-TDP-CLARO-IOL-M2", "username": "admin", "password": "admin", "via": "nombre"},
    "M3": {"host": "clab-ISP-TDP-CLARO-IOL-M3", "username": "admin", "password": "admin", "via": "nombre"},
    "M4": {"host": "clab-ISP-TDP-CLARO-IOL-M4", "username": "admin", "password": "admin", "via": "nombre"},
    "C1": {"host": "clab-ISP-TDP-CLARO-IOL-C1", "username": "admin", "password": "admin", "via": "nombre"},
    "C2": {"host": "clab-ISP-TDP-CLARO-IOL-C2", "username": "admin", "password": "admin", "via": "nombre"},
    "C3": {"host": "clab-ISP-TDP-CLARO-IOL-C3", "username": "admin", "password": "admin", "via": "nombre"},
    "C4": {"host": "clab-ISP-TDP-CLARO-IOL-C4", "username": "admin", "password": "admin", "via": "nombre"},
    "C5": {"host": "clab-ISP-TDP-CLARO-IOL-C5", "username": "admin", "password": "admin", "via": "nombre"},
    "T1": {"host": "clab-ISP-TDP-CLARO-IOL-T1", "username": "admin", "password": "admin", "via": "nombre"},
    "T2": {"host": "clab-ISP-TDP-CLARO-IOL-T2", "username": "admin", "password": "admin", "via": "nombre"},
    "T3": {"host": "clab-ISP-TDP-CLARO-IOL-T3", "username": "admin", "password": "admin", "via": "nombre"},
    "ATT1": {"host": "clab-ISP-TDP-CLARO-IOL-ATT1", "username": "admin", "password": "admin", "via": "nombre"},
    "ATT2": {"host": "clab-ISP-TDP-CLARO-IOL-ATT2", "username": "admin", "password": "admin", "via": "nombre"},
    "ATT3": {"host": "clab-ISP-TDP-CLARO-IOL-ATT3", "username": "admin", "password": "admin", "via": "nombre"},
    "OR1": {"host": "clab-ISP-TDP-CLARO-IOL-OR1", "username": "admin", "password": "admin", "via": "nombre"},
    "OR2": {"host": "clab-ISP-TDP-CLARO-IOL-OR2", "username": "admin", "password": "admin", "via": "nombre"},
    "OR3": {"host": "clab-ISP-TDP-CLARO-IOL-OR3", "username": "admin", "password": "admin", "via": "nombre"},
    "LU1": {"host": "clab-ISP-TDP-CLARO-IOL-LU1", "username": "admin", "password": "admin", "via": "nombre"},
    "LU2": {"host": "clab-ISP-TDP-CLARO-IOL-LU2", "username": "admin", "password": "admin", "via": "nombre"},
    "LU3": {"host": "clab-ISP-TDP-CLARO-IOL-LU3", "username": "admin", "password": "admin", "via": "nombre"},
    "GOOGLE": {"host": "clab-ISP-TDP-CLARO-IOL-GOOGLE", "username": "admin", "password": "admin", "via": "nombre"},
    "SW-PISO1": {"host": "clab-ISP-TDP-CLARO-IOL-SW-PISO1", "username": "admin", "password": "admin", "via": "nombre"},
    "SW-PISO2": {"host": "clab-ISP-TDP-CLARO-IOL-SW-PISO2", "username": "admin", "password": "admin", "via": "nombre"},
    "SW-R-PISO1": {"host": "clab-ISP-TDP-CLARO-IOL-SW-R-PISO1", "username": "admin", "password": "admin", "via": "nombre"},
    "SW-R-PISO2": {"host": "clab-ISP-TDP-CLARO-IOL-SW-R-PISO2", "username": "admin", "password": "admin", "via": "nombre"},
    "SW-R2-PISO1": {"host": "clab-ISP-TDP-CLARO-IOL-SW-R2-PISO1", "username": "admin", "password": "admin", "via": "nombre"},
}
